#!/bin/bash

#list process that have a process group leader with the pid located in a file in the tmp directory.
#this file is generated by the main srcipt and contains its pid
PID_FILE=
ps -f -o gid,pgid,rgid,tpgid -g 64586

